language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3 # latest before androidx
    - android-29 # this has to be your latest compilation target to accept licences
    - android-22 # do not update it is the latest on travis
    - sys-img-armeabi-v7a-android-22 # do not update it is the latest on travis
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - chmod +x gradlew
  - cd $TRAVIS_BUILD_DIR/
  - pip install --user codecov

before_script:
  # Create and start emulator
  # android-24 is the latest armeabi-v7a on travis, check before update it
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew build jacocoTestReport
  - ./gradlew check
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then ./gradlew appliveryDeploy; fi

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

after_success:
  - ./gradlew jacocoFullReport
  - codecov
  - bash <(curl -s https://codecov.io/bash)