language: android

jdk:
  - oraclejdk8

env:
  global:
  - ANDROID_TARGET=android-15
  - ANDROID_ABI=armeabi-v7a

notifications:
  slack: orchextra:edTGY2Fgw81QDHRDS3pfEixE#ci

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-24.0.3
    - build-tools-26.0.0
    - android-23
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
    - extra-android-m2repository

before_install:
   - pip install --user codecov

script:
  - ./gradlew build jacocoTestReport
  - ./gradlew check

after_success:
  - ./gradlew jacocoFullReport
  - codecov
  - bash <(curl -s https://codecov.io/bash)

