language: android
sudo: required
jdk: oraclejdk8
#This is a test pr

env:
  global:
  - ANDROID_TARGET=android-29
  - ANDROID_API_LEVEL=28
  - ANDROID_EMULATOR_API=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.0
  - ANDROID_ABI=google_apis/armeabi-v7a
  - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

notifications:
  slack:
    rooms:
      - orchextra:m4j1PrSCNml7lVi7bPexvQBP#development
    on_success: always
    on_failure: always

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-28
    - sys-img-armeabi-v7a-google_apis-google-$ANDROID_API_LEVEL
    licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+

before_install:
  - chmod +x gradlew
  - cd $TRAVIS_BUILD_DIR/
  - pip3 install --upgrade pip
  - pip3 install --user codecov

before_script:
  - echo travis launch tests v3.2.6
  - echo no | android create avd --force -n test -t android-28 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew build jacocoTestReport
  - ./gradlew check
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then ./gradlew appliveryDeploy; fi

after_success:
  - ./gradlew jacocoFullReport
  - codecov
  - bash <(curl -s https://codecov.io/bash)

