language: android

jdk:
  - oraclejdk8

env:
  global:
  - ANDROID_TARGET=android-15
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

notifications:
  slack: orchextra:edTGY2Fgw81QDHRDS3pfEixE#ci

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-24.0.3
    - build-tools-26.0.0
    - android-23
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
    - extra-android-m2repository

before_install:
  - chmod +x gradlew
  - cd $TRAVIS_BUILD_DIR/..
  - wget https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip -O ndk.zip
  - chmod a+x ndk.zip
  - unzip ndk.zip > /dev/null
  - rm ndk.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r12b
  - export PATH=$PATH:$ANDROID_NDK_HOME
  - echo $PATH
  - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
  - chmod +x install-cmake.sh
  - ./install-cmake.sh
  - cd $TRAVIS_BUILD_DIR/
  - pip install --user codecov

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew build jacocoTestReport
  - ./gradlew check

after_success:
  - ./gradlew jacocoFullReport
  - codecov
  - bash <(curl -s https://codecov.io/bash)

